export const APP = {
  INDUSTRIES: [
    {key: 'Option One', selected: false, disabled : false, display: 'block'},
    {key: 'Option Two', selected: false, disabled : false, display: 'block'},
    {key: 'Option Three', selected: false, disabled : false, display: 'block'},
    {key: 'Option Four', selected: false, disabled : false, display: 'block'},
    {key: 'Industry Served', selected: true, disabled : true, display: 'none'},
  ],
  STATES : [
    {key: 'AL', value: 'Alabama', selected: false, disabled: false, display: 'block'},
    {key: 'AK', value: 'Alaska', selected: false, disabled: false, display: 'block'},
    {key: 'AZ', value: 'Arizona', selected: false, disabled: false, display: 'block'},
    {key: 'AR', value: 'Arkansas', selected: false, disabled: false, display: 'block'},
    {key: 'CA', value: 'California', selected: false, disabled: false, display: 'block'},
    {key: 'CO', value: 'Colorado', selected: false, disabled: false, display: 'block'},
    {key: 'CT', value: 'Connecticut', selected: false, disabled: false, display: 'block'},
    {key: 'DE', value: 'Delaware', selected: false, disabled: false, display: 'block'},
    {key: 'DC', value: 'District of Columbia', selected: false, disabled: false, display: 'block'},
    {key: 'FL', value: 'Florida', selected: false, disabled: false, display: 'block'},
    {key: 'GA', value: 'Georgia', selected: false, disabled: false, display: 'block'},
    {key: 'HI', value: 'Hawaii', selected: false, disabled: false, display: 'block'},
    {key: 'ID', value: 'Idaho', selected: false, disabled: false, display: 'block'},
    {key: 'IL', value: 'Illinois', selected: false, disabled: false, display: 'block'},
    {key: 'IN', value: 'Indiana', selected: false, disabled: false, display: 'block'},
    {key: 'IA', value: 'Iowa', selected: false, disabled: false, display: 'block'},
    {key: 'KS', value: 'Kansas', selected: false, disabled: false, display: 'block'},
    {key: 'KY', value: 'Kentucky', selected: false, disabled: false, display: 'block'},
    {key: 'LA', value: 'Louisiana', selected: false, disabled: false, display: 'block'},
    {key: 'ME', value: 'Maine', selected: false, disabled: false, display: 'block'},
    {key: 'MD', value: 'Maryland', selected: false, disabled: false, display: 'block'},
    {key: 'MA', value: 'Massachusetts', selected: false, disabled: false, display: 'block'},
    {key: 'MI', value: 'Michigan', selected: false, disabled: false, display: 'block'},
    {key: 'MN', value: 'Minnesota', selected: false, disabled: false, display: 'block'},
    {key: 'MS', value: 'Mississippi', selected: false, disabled: false, display: 'block'},
    {key: 'MO', value: 'Missouri', selected: false, disabled: false, display: 'block'},
    {key: 'MT', value: 'Montana', selected: false, disabled: false, display: 'block'},
    {key: 'NE', value: 'Nebraska', selected: false, disabled: false, display: 'block'},
    {key: 'NV', value: 'Nevada', selected: false, disabled: false, display: 'block'},
    {key: 'NH', value: 'New Hampshire', selected: false, disabled: false, display: 'block'},
    {key: 'NJ', value: 'New Jersey', selected: false, disabled: false, display: 'block'},
    {key: 'NM', value: 'New Mexico', selected: false, disabled: false, display: 'block'},
    {key: 'NY', value: 'New York', selected: false, disabled: false, display: 'block'},
    {key: 'NC', value: 'North Carolina', selected: false, disabled: false, display: 'block'},
    {key: 'ND', value: 'North Dakota', selected: false, disabled: false, display: 'block'},
    {key: 'OH', value: 'Ohio', selected: false, disabled: false, display: 'block'},
    {key: 'OK', value: 'Oklahoma', selected: false, disabled: false, display: 'block'},
    {key: 'OR', value: 'Oregon', selected: false, disabled: false, display: 'block'},
    {key: 'PA', value: 'Pennsylvania', selected: false, disabled: false, display: 'block'},
    {key: 'RI', value: 'Rhode Island', selected: false, disabled: false, display: 'block'},
    {key: 'SC', value: 'South Carolina', selected: false, disabled: false, display: 'block'},
    {key: 'SD', value: 'South Dakota', selected: false, disabled: false, display: 'block'},
    {key: 'TN', value: 'Tennessee', selected: false, disabled: false, display: 'block'},
    {key: 'TX', value: 'Texas', selected: false, disabled: false, display: 'block'},
    {key: 'UT', value: 'Utah', selected: false, disabled: false, display: 'block'},
    {key: 'VT', value: 'Vermont', selected: false, disabled: false, display: 'block'},
    {key: 'VA', value: 'Virginia', selected: false, disabled: false, display: 'block'},
    {key: 'WA', value: 'Washington', selected: false, disabled: false, display: 'block'},
    {key: 'WV', value: 'West Virginia', selected: false, disabled: false, display: 'block'},
    {key: 'WI', value: 'Wisconsin', selected: false, disabled: false, display: 'block'},
    {key: 'WY', value: 'Wyoming', selected: false, disabled: false, display: 'block'},
    {key: 'State', value: 'State', selected: true, disabled: true, display: 'none'},

  ]
}
